# Generated by Django 2.2.3 on 2019-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190730_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.TextField(choices=[('Python', 'python'), ('JAVA', 'java'), ('.NET', '.net'), ('C', 'c'), ('C++', 'c++'), ('HTML', 'html'), ('CSS', 'css')], default=None),
        ),
    ]
